### ISSUE TITLE
ldap报错 Error initializing SSL/TLS, data 0, v3839

### ISSUE THREAD

**Issue by Li-RuiXian** [icyxp/kubernetes-dashboard-ldap#5]
选择AD Login登录，输入完用户密码后的完整报错为：
LDAP Result Code 52 "Unavailable": 00000000: LdapErr: DSID-0C0912C4, comment: Error initializing SSL/TLS, data 0, v3839
请问该如何调整，谢谢。

**Comment by icyxp** [comment]
Can you provide configuration information related to ldap? like this
```
ldap:
  addr: ldap://192.168.3.81:389
  adminUser: xxxxx
  adminPwd: xxxxxx
  baseDN: dc=corp,dc=xp,dc=com
  filter: (&(objectClass=person)(sAMAccountName=%s))
```
Can ldap use port 389？In the code, I skip tls verification.
```
tls.Config{InsecureSkipVerify: true}
```
